// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-cc/ent/schema"
	"go-cc/ent/seat"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	seatFields := schema.Seat{}.Fields()
	_ = seatFields
	// seatDescIsBooked is the schema descriptor for is_booked field.
	seatDescIsBooked := seatFields[1].Descriptor()
	// seat.DefaultIsBooked holds the default value on creation for the is_booked field.
	seat.DefaultIsBooked = seatDescIsBooked.Default.(bool)
	// seatDescVersion is the schema descriptor for version field.
	seatDescVersion := seatFields[3].Descriptor()
	// seat.DefaultVersion holds the default value on creation for the version field.
	seat.DefaultVersion = seatDescVersion.Default.(uint64)
}
